ID_001 Bacillus -> 
ID_002 Clostridium -> Clostridia (106); unnamed (138); Clostridium (83)
ID_003 Clostridium -> Clostridia (106); unnamed (138); Clostridium (83)
ID_004 Bacillus -> 
ID_005 Bacillus -> Bacilli (84); Bacillaceae (89); Bacillus (104)
ID_006 Bacillus -> Bacilli (84); Bacillaceae (89); Bacillus (104)
ID_007 Exiguobacterium -> 
ID_008 Clostridium -> Clostridia (131); unnamed (200); Clostridium (179)
ID_009 Sporomusa -> 
ID_010 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_011 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_012 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_013 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_014 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_015 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_016 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_017 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_018 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_019 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_020 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_021 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_022 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_023 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_024 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_025 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_026 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_027 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_028 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_029 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_030 Clostridium -> Clostridia (180); unnamed (218); Clostridium (175)
ID_031 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_032 Clostridium -> Clostridia (166); unnamed (209); Clostridium (169)
ID_033 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_034 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_035 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_036 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_037 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_038 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_039 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_040 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_041 Clostridium -> Clostridia (169); unnamed (203); Clostridium (166)
ID_042 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_043 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_044 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_045 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_046 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_047 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_048 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_049 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_050 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_051 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_052 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_053 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_054 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_055 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_056 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_057 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_058 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_059 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_060 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_061 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_062 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_063 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_064 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_065 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_066 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_067 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_068 Clostridium -> Clostridia (170); unnamed (207); Clostridium (170)
ID_069 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_070 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_071 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_072 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_073 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_074 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_075 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_076 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_077 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_078 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_079 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_080 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_081 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_082 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_083 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_084 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_085 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_086 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_087 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_088 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_089 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_090 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_091 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_092 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_093 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_094 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_095 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_096 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_097 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_098 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_099 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_100 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_101 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_102 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_103 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_104 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_105 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_106 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_107 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_108 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_109 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_110 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_111 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_112 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_113 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_114 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_115 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_116 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_117 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_118 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_119 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_120 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_121 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_122 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_123 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_124 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_125 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_126 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_127 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_128 Clostridium -> Clostridia (172); unnamed (209); Clostridium (169)
ID_129 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_130 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_131 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_132 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_133 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_134 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_135 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_136 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_137 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_138 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_139 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_140 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_141 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_142 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_143 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_144 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_145 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_146 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_147 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_148 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_149 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_150 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_151 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_152 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_153 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_154 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_155 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_156 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_157 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_158 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_159 Clostridium -> Clostridia (188); unnamed (222); Clostridium (186)
ID_160 Clostridium -> Clostridia (191); unnamed (232); Clostridium (187)
ID_161 Clostridium -> Clostridia (172); unnamed (210); Clostridium (170)
ID_162 Clostridium -> Clostridia (191); unnamed (232); Clostridium (187)
ID_163 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_164 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_165 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_166 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_167 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_168 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_169 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_170 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_171 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_172 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_173 Clostridium -> Clostridia (135); unnamed (203); Clostridium (176)
ID_174 Clostridium -> Clostridia (138); unnamed (197); Clostridium (174)
ID_175 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_176 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_177 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_178 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_179 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_180 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_181 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_182 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_183 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_184 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_185 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_186 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_187 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_188 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_189 Bacillus -> 
ID_190 Bacillus -> 
ID_191 Bacillus -> 
ID_192 Bacillus -> 
ID_193 Clostridium -> Clostridia (142); unnamed (180); Clostridium (162)
ID_194 Clostridium -> Clostridia (105); unnamed (162); Clostridium (159)
ID_195 Clostridium -> Clostridia (172); unnamed (209); Clostridium (169)
ID_196 C_innocuum -> Erysipelotrichia (108); C_innocuum (108)
ID_197 Clostridium -> Clostridia (131); unnamed (177); Clostridium (150)
ID_198 Geobacillus -> 
ID_199 Lysinibacillus -> 
ID_200 Moorella -> Clostridia (105)
ID_201 Clostridium -> Clostridia (121); unnamed (164); Clostridium (162)
ID_202 Bacillus -> 
ID_203 Clostridium -> Clostridia (117); unnamed (176); Clostridium (153)
ID_204 Bacillus -> 
ID_205 Clostridium -> Clostridia (114); unnamed (168); Clostridium (160)
ID_206 Clostridium -> Clostridia (182); unnamed (220); Clostridium (170)
ID_207 Bacillus -> 
ID_208 Desmospora -> 
ID_209 Bacillus -> 
ID_210 Bacillus -> Bacilli (94); Bacillaceae (106); Bacillus (90)
ID_211 Clostridium -> Clostridia (108); unnamed (189)
ID_212 Bacillus -> 
ID_213 Dehalobacter -> Clostridia (130); unnamed (157); unnamed (127); Dehalobacter (256)
ID_214 Pseudoflavonifractor -> Clostridia (301); unnamed (*); Pseudoflavonifractor (*)
ID_215 Bacillus -> 
ID_216 Bacillus -> 
ID_217 Turicibacter -> Erysipelotrichia (85); Turicibacter (*)
ID_218 Bacillus -> 
ID_219 Clostridium -> Clostridia (125); unnamed (225)
ID_220 Brevibacillus -> 
ID_221 Bacillus -> 
ID_222 Bacillus -> 
ID_223 Clostridium -> Clostridia (125); unnamed (182); Clostridium (141)
ID_224 Clostridium -> Clostridia (110); unnamed (183); Clostridium (136)
ID_225 Clostridium -> Clostridia (127); unnamed (172); Clostridium (153)
ID_226 Bacillus -> 
ID_227 Bacillus -> 
ID_228 Anaerostipes -> Clostridia (222); unnamed (262); unnamed (225); Anaerostipes (*)
ID_229 Anaerostipes -> Clostridia (128); unnamed (219); unnamed (118); Anaerostipes (222)
ID_230 Paenibacillus -> 
ID_231 Dehalobacter -> Clostridia (130); unnamed (157); unnamed (127); Dehalobacter (256)
ID_232 Bacillus -> 
ID_233 Bacillus -> 
ID_234 Clostridium -> Clostridia (105); unnamed (162); Clostridium (159)
ID_235 Bacillus -> 
ID_236 Clostridium -> Clostridia (132); unnamed (173); Clostridium (137)
ID_237 Clostridium -> Clostridia (124); unnamed (180); Clostridium (141)
ID_238 Bacillus -> Bacilli (84); Bacillaceae (89); Bacillus (104)
ID_239 Sporosarcina -> 
ID_240 Carboxydibrachium -> Clostridia (112)
ID_241 Clostridium -> Clostridia (124); unnamed (180); Clostridium (141)
ID_242 Bacillus -> 
ID_243 Ruminococcus -> Clostridia (136); unnamed (219)
ID_244 Brevibacillus -> 
ID_245 Clostridium -> Clostridia (124); unnamed (180); Clostridium (141)
ID_246 Clostridium -> Clostridia (176); unnamed (236)
ID_247 Clostridium -> Clostridia (118); unnamed (180); Clostridium (158)
ID_248 Clostridium -> Clostridia (114); unnamed (168); Clostridium (160)
ID_249 Bacillus -> 
ID_250 Bacillus -> 
ID_251 Paenibacillus -> 
ID_252 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_253 Geobacillus -> 
ID_254 Clostridium -> Clostridia (171); unnamed (206); Clostridium (166)
ID_255 Pasteuria -> 
ID_256 Synechocystis -> 
ID_257 Clostridium -> Clostridia (88); unnamed (156); Clostridium (130)
ID_258 Bacillus -> 
ID_259 Bacillus -> 
ID_260 Bacillus -> 
ID_261 Eubacterium -> Clostridia (174); unnamed (240); unnamed (86); Eubacterium (*)
ID_262 Eubacterium -> Clostridia (119); unnamed (193)
ID_263 Bacillus -> Bacilli (84); Bacillaceae (89); Bacillus (104)
ID_264 Paenibacillus -> 
ID_265 Anoxybacillus -> 
ID_266 Clostridium -> Clostridia (124); unnamed (180); Clostridium (141)
ID_267 Geobacillus -> 
ID_268 E_dolichum -> Erysipelotrichia (94); E_dolichum (100)
ID_269 Clostridium -> Clostridia (100); unnamed (139); Clostridium (144)
ID_270 C_ultunense -> 
ID_271 Bacillus -> 
ID_272 Anaerofustis -> Clostridia (114); unnamed (107); unnamed (107); Anaerofustis (*)
ID_273 Desulfotomaculum -> 
ID_274 Paenibacillus -> 
ID_275 Dorea -> Clostridia (165); unnamed (212); unnamed (92); Dorea (207)
ID_276 Bacillus -> 
ID_277 Bacillus -> 
ID_278 Clostridium -> Clostridia (132); unnamed (173); Clostridium (137)
ID_279 Clostridium -> Clostridia (124); unnamed (180); Clostridium (141)
ID_280 Clostridium -> Clostridia (106); unnamed (166); Clostridium (145)
ID_281 Bhargavaea -> 
ID_282 Marvinbryantia -> Clostridia (134); unnamed (184)
ID_283 Clostridium -> Clostridia (147); unnamed (218); Clostridium (107)
ID_284 Clostridium -> Clostridia (132); unnamed (173); Clostridium (137)
ID_285 Bacillus -> 
ID_286 Dorea -> Clostridia (166); unnamed (232); unnamed (125); Dorea (272)
ID_287 Turicibacter -> Erysipelotrichia (85); Turicibacter (*)
ID_288 Paenibacillus -> 
ID_289 Bacillus -> Bacilli (84); Bacillaceae (89); Bacillus (104)
ID_290 Bacillus -> 
ID_291 Clostridium -> Clostridia (132); unnamed (173); Clostridium (137)
ID_292 Clostridium -> Clostridia (99); unnamed (169)
ID_293 Bacillus -> 
ID_294 Clostridium -> Clostridia (132); unnamed (173); Clostridium (137)
ID_295 Clostridium -> Clostridia (132); unnamed (173); Clostridium (137)
ID_296 Clostridium -> Clostridia (120); unnamed (179); Clostridium (159)
ID_297 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_298 Bacillus -> 
ID_299 Clostridium -> Clostridia (122); unnamed (174); Clostridium (139)
ID_300 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_301 Carboxydothermus -> 
ID_302 Paenibacillus -> 
ID_303 Clostridium -> Clostridia (132); unnamed (173); Clostridium (137)
ID_304 Clostridium -> Clostridia (170); unnamed (208); Clostridium (168)
ID_305 Bacillus -> 
ID_306 Bacillus -> 
ID_307 Bacillus -> Bacilli (84); Bacillaceae (89); Bacillus (104)
ID_308 Bacillus -> 
ID_309 Symbiobacterium -> Clostridia (155); unnamed (167); Symbiobacterium (210)
ID_310 Symbiobacterium -> Clostridia (185); unnamed (269); Symbiobacterium (223)
ID_311 Bacillus -> 
ID_312 Clostridium -> Clostridia (132); unnamed (173); Clostridium (137)
ID_313 Bacillus -> 
ID_314 Clostridium -> Clostridia (133); unnamed (173); Clostridium (131)
ID_315 Clostridium -> Clostridia (110); unnamed (159); Clostridium (153)
ID_316 Bacillus -> 
ID_317 Oscillibacter -> Clostridia (159); unnamed (198); Oscillibacter (122)
ID_318 Bacillus -> Bacilli (85); Bacillaceae (88); Bacillus (107)
ID_319 Exiguobacterium -> 
ID_320 Bacillus -> 
ID_321 Bacillus -> 
ID_322 Geobacillus -> 
ID_323 Clostridium -> Clostridia (128); unnamed (173); Clostridium (155)
ID_324 Clostridium -> Clostridia (124); unnamed (180); Clostridium (141)
ID_325 Bacillus -> 
ID_326 Anoxybacillus -> 
ID_327 Bacillus -> Bacilli (94); Bacillaceae (106); Bacillus (90)
ID_328 Bacillus -> 
ID_329 Bacillus -> 
ID_330 Clostridium -> Clostridia (109); unnamed (158); Clostridium (111)
ID_331 Bacillus -> 
ID_332 Bacillus -> 
ID_333 Thermacetogenium -> Clostridia (97)
ID_334 Clostridium -> Clostridia (132); unnamed (173); Clostridium (137)
ID_335 Oceanobacillus -> 
ID_336 Bacillus -> 
ID_337 Bacillus -> 
ID_338 Bacillus -> 
ID_339 Clostridium -> Clostridia (207); unnamed (281); Clostridium (193)
ID_340 Bacillus -> 
ID_341 Brevibacillus -> 
ID_342 Bacillus -> Bacilli (94); Bacillaceae (106); Bacillus (90)
ID_343 Alicyclobacillus -> 
ID_344 Sulfobacillus -> Clostridia (87); unnamed (128)
ID_345 Amphibacillus -> 
ID_346 Clostridium -> Clostridia (125); unnamed (176); Clostridium (143)
ID_347 Heliobacterium -> Clostridia (83)
ID_348 Bacillus -> 
ID_349 Anaerostipes -> Clostridia (216); unnamed (254); unnamed (218); Anaerostipes (*)
ID_350 Anaerostipes -> Clostridia (128); unnamed (219); unnamed (118); Anaerostipes (222)
ID_351 Anaerostipes -> Clostridia (216); unnamed (254); unnamed (218); Anaerostipes (*)
ID_352 Anaerostipes -> Clostridia (128); unnamed (219); unnamed (118); Anaerostipes (222)
ID_353 Anaerostipes -> Clostridia (108); unnamed (189)
ID_354 Anaerostipes -> Clostridia (201); unnamed (241); unnamed (210); Anaerostipes (*)
ID_355 Anaerostipes -> Clostridia (234); unnamed (306); unnamed (293); Anaerostipes (*)
ID_356 Anaerostipes -> Clostridia (128); unnamed (219); unnamed (118); Anaerostipes (222)
ID_357 Anaerostipes -> Clostridia (216); unnamed (254); unnamed (218); Anaerostipes (*)
ID_358 Dorea -> Clostridia (165); unnamed (212); unnamed (92); Dorea (207)
ID_359 Dorea -> Clostridia (166); unnamed (232); unnamed (125); Dorea (272)
ID_360 Dorea -> Clostridia (162); unnamed (211); unnamed (90); Dorea (207)
ID_361 Dorea -> Clostridia (164); unnamed (233)
ID_362 Dorea -> Clostridia (166); unnamed (232); unnamed (125); Dorea (272)
