ID_001 -> Bacilli (56); Bacillaceae (97); Bacillus (87): -114875
ID_002 -> Clostridia (106); unnamed (138); Clostridium (83): -137003
ID_003 -> Clostridia (106); unnamed (138); Clostridium (83): -137003
ID_004 -> Bacilli (79); Bacillaceae (95); Bacillus (99): -72461
ID_005 -> Bacilli (84); Bacillaceae (89); Bacillus (104): -69712
ID_006 -> Bacilli (84); Bacillaceae (89); Bacillus (104): -69712
ID_007 -> Bacilli (80); Exiguobacterium (279): -106213
ID_008 -> Clostridia (131); unnamed (200); Clostridium (179): -40447
ID_009 -> Clostridia (74); Sporomusa (30): -96000
ID_010 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_011 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_012 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_013 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_014 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_015 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_016 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_017 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_018 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_019 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_020 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_021 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_022 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_023 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_024 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_025 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_026 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_027 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_028 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_029 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_030 -> Clostridia (180); unnamed (218); Clostridium (175): -23247
ID_031 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_032 -> Clostridia (166); unnamed (209); Clostridium (169): -16903
ID_033 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_034 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_035 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_036 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_037 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_038 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_039 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_040 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_041 -> Clostridia (169); unnamed (203); Clostridium (166): -15837
ID_042 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_043 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_044 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_045 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_046 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_047 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_048 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_049 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_050 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_051 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_052 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_053 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_054 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_055 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_056 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_057 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_058 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_059 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_060 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_061 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_062 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_063 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_064 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_065 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_066 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_067 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_068 -> Clostridia (170); unnamed (207); Clostridium (170): -18847
ID_069 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_070 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_071 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_072 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_073 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_074 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_075 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_076 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_077 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_078 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_079 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_080 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_081 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_082 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_083 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_084 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_085 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_086 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_087 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_088 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_089 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_090 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_091 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_092 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_093 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_094 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_095 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_096 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_097 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_098 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_099 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_100 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_101 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_102 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_103 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_104 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_105 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_106 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_107 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_108 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_109 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_110 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_111 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_112 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_113 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_114 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_115 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_116 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_117 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_118 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_119 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_120 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_121 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_122 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_123 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_124 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_125 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_126 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_127 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_128 -> Clostridia (172); unnamed (209); Clostridium (169): -17070
ID_129 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_130 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_131 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_132 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_133 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_134 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_135 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_136 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_137 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_138 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_139 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_140 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_141 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_142 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_143 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_144 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_145 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_146 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_147 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_148 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_149 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_150 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_151 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_152 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_153 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_154 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_155 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_156 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_157 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_158 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_159 -> Clostridia (188); unnamed (222); Clostridium (186): -46004
ID_160 -> Clostridia (191); unnamed (232); Clostridium (187): -43744
ID_161 -> Clostridia (172); unnamed (210); Clostridium (170): -16568
ID_162 -> Clostridia (191); unnamed (232); Clostridium (187): -43744
ID_163 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_164 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_165 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_166 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_167 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_168 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_169 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_170 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_171 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_172 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_173 -> Clostridia (135); unnamed (203); Clostridium (176): -48344
ID_174 -> Clostridia (138); unnamed (197); Clostridium (174): -51901
ID_175 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_176 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_177 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_178 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_179 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_180 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_181 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_182 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_183 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_184 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_185 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_186 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_187 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_188 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_189 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_190 -> Bacilli (71); Bacillaceae (101); Bacillus (79): -90687
ID_191 -> Bacilli (79); Bacillaceae (95); Bacillus (99): -72461
ID_192 -> Bacilli (71); Bacillaceae (101); Bacillus (79): -90687
ID_193 -> Clostridia (142); unnamed (180); Clostridium (162): -105989
ID_194 -> Clostridia (105); unnamed (162); Clostridium (159): -89716
ID_195 -> Clostridia (172); unnamed (209); Clostridium (169): -17081
ID_196 -> Erysipelotrichia (108); C_innocuum (108): -120000
ID_197 -> Clostridia (131); unnamed (177); Clostridium (150): -109859
ID_198 -> Bacilli (58); Bacillaceae (85); Geobacillus (44): -94232
ID_199 -> Bacilli (66); Bacillaceae (142); Lysinibacillus (167): -92000
ID_200 -> Clostridia (105); Thermoanaerobacteraceae (1); Moorella (124): -108000
ID_201 -> Clostridia (121); unnamed (164); Clostridium (162): -82024
ID_202 -> Bacilli (71); Bacillaceae (101); Bacillus (79): -90687
ID_203 -> Clostridia (117); unnamed (176); Clostridium (153): -92461
ID_204 -> Bacilli (79); Bacillaceae (95); Bacillus (99): -72461
ID_205 -> Clostridia (114); unnamed (168); Clostridium (160): -94854
ID_206 -> Clostridia (182); unnamed (220); Clostridium (170): -27578
ID_207 -> Bacilli (79); Bacillaceae (95); Bacillus (99): -72461
ID_208 -> Bacilli (11); Desmospora (86): -76000
ID_209 -> Bacilli (71); Bacillaceae (99); Bacillus (85): -92264
ID_210 -> Bacilli (94); Bacillaceae (106); Bacillus (90): -71667
ID_211 -> Clostridia (108); unnamed (189); unnamed (54); Anaerostipes (174): -124113
ID_212 -> Bacilli (71); Bacillaceae (101); Bacillus (79): -90687
ID_213 -> Clostridia (130); unnamed (157); unnamed (127); Dehalobacter (256): -124000
ID_214 -> Clostridia (301); unnamed (*); Pseudoflavonifractor (*): -104000
ID_215 -> Bacilli (79); Bacillaceae (95); Bacillus (99): -72461
ID_216 -> Bacilli (53); Bacillaceae (95); Bacillus (83): -119463
ID_217 -> Erysipelotrichia (85); Turicibacter (*): -52000
ID_218 -> Bacilli (79); Bacillaceae (95); Bacillus (99): -72461
ID_219 -> Clostridia (125); unnamed (225); Clostridium (59): -176353
ID_220 -> Bacilli (24); Paenibacillaceae (50); Brevibacillus (130): -79168
ID_221 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_222 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_223 -> Clostridia (125); unnamed (182); Clostridium (141): -119099
ID_224 -> Clostridia (110); unnamed (183); Clostridium (136): -92816
ID_225 -> Clostridia (127); unnamed (172); Clostridium (153): -83414
ID_226 -> Bacilli (73); Bacillaceae (101); Bacillus (83): -90437
ID_227 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_228 -> Clostridia (222); unnamed (262); unnamed (225); Anaerostipes (*): -77945
ID_229 -> Clostridia (128); unnamed (219); unnamed (118); Anaerostipes (222): -74830
ID_230 -> Bacilli (23); Paenibacillaceae (99); Paenibacillus (138): -97284
ID_231 -> Clostridia (130); unnamed (157); unnamed (127); Dehalobacter (256): -124000
ID_232 -> Bacilli (56); Bacillaceae (88); Bacillus (75): -115361
ID_233 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_234 -> Clostridia (105); unnamed (162); Clostridium (159): -89716
ID_235 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_236 -> Clostridia (132); unnamed (173); Clostridium (137): -91398
ID_237 -> Clostridia (124); unnamed (180); Clostridium (141): -116654
ID_238 -> Bacilli (84); Bacillaceae (89); Bacillus (104): -69712
ID_239 -> Bacilli (38); Sporosarcina (100): -120000
ID_240 -> Clostridia (112); Thermoanaerobacteraceae (32); Carboxydibrachium (284): -76000
ID_241 -> Clostridia (124); unnamed (180); Clostridium (141): -116654
ID_242 -> Bacilli (79); Bacillaceae (95); Bacillus (99): -72461
ID_243 -> Clostridia (136); unnamed (219); Ruminococcus (19): -132000
ID_244 -> Bacilli (24); Paenibacillaceae (50); Brevibacillus (130): -79168
ID_245 -> Clostridia (124); unnamed (180); Clostridium (141): -116654
ID_246 -> Clostridia (176); unnamed (236); unnamed (64); Dorea (182): -106057
ID_247 -> Clostridia (118); unnamed (180); Clostridium (158): -77325
ID_248 -> Clostridia (114); unnamed (168); Clostridium (160): -94854
ID_249 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_250 -> Bacilli (70); Bacillaceae (103); Bacillus (78): -91904
ID_251 -> Bacilli (31); Paenibacillaceae (111); Paenibacillus (135): -77098
ID_252 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_253 -> Bacilli (50); Bacillaceae (86); Geobacillus (33): -114232
ID_254 -> Clostridia (171); unnamed (206); Clostridium (166): -16737
ID_255 -> Bacilli (58); Pasteuria (123): -64000
ID_256 -> Bacilli (79); Bacillaceae (95); Bacillus (99): -72461
ID_257 -> Clostridia (88); unnamed (156); Clostridium (130): -144681
ID_258 -> Bacilli (79); Bacillaceae (95); Bacillus (99): -72461
ID_259 -> Bacilli (79); Bacillaceae (95); Bacillus (99): -72461
ID_260 -> Bacilli (70); Bacillaceae (103); Bacillus (78): -91904
ID_261 -> Clostridia (174); unnamed (240); unnamed (86); Eubacterium (*): -121988
ID_262 -> Clostridia (119); unnamed (193); unnamed (7); Eubacterium (275): -169228
ID_263 -> Bacilli (84); Bacillaceae (89); Bacillus (104): -69712
ID_264 -> Bacilli (0); Paenibacillaceae (91); Paenibacillus (127): -140668
ID_265 -> Bacilli (45); Bacillaceae (81); Anoxybacillus (39): -108903
ID_266 -> Clostridia (124); unnamed (180); Clostridium (141): -116654
ID_267 -> Bacilli (59); Bacillaceae (82); Geobacillus (39): -94709
ID_268 -> Erysipelotrichia (94); E_dolichum (100): -112000
ID_269 -> Clostridia (100); unnamed (139); Clostridium (144): -123055
ID_270 -> Clostridia (21); unnamed (143); Clostridium (50): -178059
ID_271 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_272 -> Clostridia (114); unnamed (107); unnamed (107); Anaerofustis (*): -48000
ID_273 -> Clostridia (66); unnamed (35); unnamed (92); Desulfotomaculum (296): -68000
ID_274 -> Bacilli (31); Paenibacillaceae (117); Paenibacillus (135): -77943
ID_275 -> Clostridia (165); unnamed (212); unnamed (92); Dorea (207): -51966
ID_276 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_277 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_278 -> Clostridia (132); unnamed (173); Clostridium (137): -91398
ID_279 -> Clostridia (124); unnamed (180); Clostridium (141): -116654
ID_280 -> Clostridia (106); unnamed (166); Clostridium (145): -85729
ID_281 -> Clostridia (7); unnamed (171); Clostridium (46): -220367
ID_282 -> Clostridia (134); unnamed (184); unnamed (57); Marvinbryantia (127): -84000
ID_283 -> Clostridia (147); unnamed (218); Clostridium (107): -192017
ID_284 -> Clostridia (132); unnamed (173); Clostridium (137): -91398
ID_285 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_286 -> Clostridia (166); unnamed (232); unnamed (125); Dorea (272): -25054
ID_287 -> Erysipelotrichia (85); Turicibacter (*): -52000
ID_288 -> Bacilli (42); Paenibacillaceae (132); Paenibacillus (167): -80199
ID_289 -> Bacilli (84); Bacillaceae (89); Bacillus (104): -69712
ID_290 -> Bacilli (79); Bacillaceae (95); Bacillus (99): -72461
ID_291 -> Clostridia (132); unnamed (173); Clostridium (137): -91398
ID_292 -> Clostridia (99); unnamed (169); Clostridium (71): -171533
ID_293 -> Bacilli (56); Bacillaceae (97); Bacillus (87): -114875
ID_294 -> Clostridia (132); unnamed (173); Clostridium (137): -91398
ID_295 -> Clostridia (132); unnamed (173); Clostridium (137): -91398
ID_296 -> Clostridia (120); unnamed (179); Clostridium (159): -95005
ID_297 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_298 -> Bacilli (53); Bacillaceae (92); Bacillus (79): -118722
ID_299 -> Clostridia (122); unnamed (174); Clostridium (139): -87912
ID_300 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_301 -> Clostridia (73); Thermoanaerobacteraceae (4); Carboxydothermus (136): -144000
ID_302 -> Bacilli (19); Paenibacillaceae (93); Paenibacillus (131): -124551
ID_303 -> Clostridia (132); unnamed (173); Clostridium (137): -91398
ID_304 -> Clostridia (170); unnamed (208); Clostridium (168): -14622
ID_305 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_306 -> Bacilli (30); Bacillaceae (79); Bacillus (88): -153101
ID_307 -> Bacilli (84); Bacillaceae (89); Bacillus (104): -69712
ID_308 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_309 -> Clostridia (155); unnamed (167); Symbiobacterium (210): -98916
ID_310 -> Clostridia (185); unnamed (269); Symbiobacterium (223): -167906
ID_311 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_312 -> Clostridia (132); unnamed (173); Clostridium (137): -91398
ID_313 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_314 -> Clostridia (133); unnamed (173); Clostridium (131): -93746
ID_315 -> Clostridia (110); unnamed (159); Clostridium (153): -100411
ID_316 -> Bacilli (49); Bacillaceae (82); Bacillus (126): -99928
ID_317 -> Clostridia (159); unnamed (198); Oscillibacter (122): -112000
ID_318 -> Bacilli (85); Bacillaceae (88); Bacillus (107): -70889
ID_319 -> Bacilli (18); Exiguobacterium (236): -149609
ID_320 -> Bacilli (79); Bacillaceae (95); Bacillus (99): -72461
ID_321 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_322 -> Bacilli (50); Bacillaceae (86); Geobacillus (33): -114232
ID_323 -> Clostridia (128); unnamed (173); Clostridium (155): -85336
ID_324 -> Clostridia (124); unnamed (180); Clostridium (141): -116654
ID_325 -> Bacilli (71); Bacillaceae (101); Bacillus (79): -90687
ID_326 -> Bacilli (51); Bacillaceae (87); Anoxybacillus (69): -81204
ID_327 -> Bacilli (94); Bacillaceae (106); Bacillus (90): -71667
ID_328 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_329 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_330 -> Clostridia (109); unnamed (158); Clostridium (111): -114337
ID_331 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_332 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_333 -> Clostridia (97); unnamed (3); Clostridium (10): -196652
ID_334 -> Clostridia (132); unnamed (173); Clostridium (137): -91398
ID_335 -> Bacilli (53); Bacillaceae (75); Oceanobacillus (89): -88000
ID_336 -> Bacilli (71); Bacillaceae (101); Bacillus (79): -90687
ID_337 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_338 -> Bacilli (71); Bacillaceae (101); Bacillus (83): -90437
ID_339 -> Clostridia (207); unnamed (281); Clostridium (193): -193046
ID_340 -> Bacilli (71); Bacillaceae (101); Bacillus (79): -90687
ID_341 -> Bacilli (13); Paenibacillaceae (21); Brevibacillus (118): -141122
ID_342 -> Bacilli (94); Bacillaceae (106); Bacillus (90): -71667
ID_343 -> Bacilli (16); Alicyclobacillus (137): -148000
ID_344 -> Clostridia (87); unnamed (128); Sulfobacillus (68): -96000
ID_345 -> Bacilli (52); Bacillaceae (113); Amphibacillus (103): -92000
ID_346 -> Clostridia (125); unnamed (176); Clostridium (143): -120682
ID_347 -> Clostridia (83); unnamed (63); Heliobacterium (93): -92000
ID_348 -> Bacilli (72); Bacillaceae (93); Bacillus (116): -102256
ID_349 -> Clostridia (216); unnamed (254); unnamed (218); Anaerostipes (*): -75498
ID_350 -> Clostridia (128); unnamed (219); unnamed (118); Anaerostipes (222): -74830
ID_351 -> Clostridia (216); unnamed (254); unnamed (218); Anaerostipes (*): -75498
ID_352 -> Clostridia (128); unnamed (219); unnamed (118); Anaerostipes (222): -74830
ID_353 -> Clostridia (108); unnamed (189); unnamed (54); Anaerostipes (174): -124113
ID_354 -> Clostridia (201); unnamed (241); unnamed (210); Anaerostipes (*): -98052
ID_355 -> Clostridia (234); unnamed (306); unnamed (293); Anaerostipes (*): -86740
ID_356 -> Clostridia (128); unnamed (219); unnamed (118); Anaerostipes (222): -74830
ID_357 -> Clostridia (216); unnamed (254); unnamed (218); Anaerostipes (*): -75498
ID_358 -> Clostridia (165); unnamed (212); unnamed (92); Dorea (207): -51966
ID_359 -> Clostridia (166); unnamed (232); unnamed (125); Dorea (272): -25054
ID_360 -> Clostridia (162); unnamed (211); unnamed (90); Dorea (207): -55329
ID_361 -> Clostridia (164); unnamed (233); unnamed (78); Dorea (241): -53202
ID_362 -> Clostridia (166); unnamed (232); unnamed (125); Dorea (272): -25054
